import React from "react";
import "../assets/css/PrivacyPolicy.css";

const PrivacyPolicy = () => {
  return (
    <div>
      <div className="container termsconditions">
        <div className="row">
          <h2 className="text-center"><strong>Privacy Policy</strong></h2>
          <br />
          <br />
      <p style={{textAlign:"justify"}} className="showContent">

<span>Melisxpress LLC ("us", "we", or "our") operates the www.melisxpress.com website (hereinafter referred to as the "Service").</span><br/>

<span>This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.</span><br/>

<span>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from www.melisxpress.com</span>

</p>
          <br />

          <h3><strong>Definitions:</strong></h3>
          <ul className="role-ul">
            <li className="role-li">
              <strong>Service</strong>
              <span>
                Service is the www.melisxpress.com website operated by Melisxpress LLC.
              </span>
            </li>
            <li className="role-li">
            <strong>Personal Data</strong>
              <span>
              Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
              </span>
            </li>
            <li className="role-li">
            <strong>Usage Data</strong>
              <span>
                Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
              </span>
            </li>
            <li className="role-li">
            <strong>Cookies</strong>
              <span>
                Cookies are small files stored on your device (computer or mobile device).
              </span>
            </li>
            <li className="role-li">
            <strong>Data Controller</strong>
              <span>
              Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.
              <br/>
              For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.
              </span>
            </li>
            <li className="role-li">
            <strong>Data Processors (or Service Providers)</strong>
              <span>
                Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.
                <br/>
                We may use the services of various Service Providers in order to process your data more effectively.
              </span>
            </li>
            <li className="role-li">
            <strong>Data Subject (or User)</strong>
              <span>
                Data Subject is any living individual who is using our Service and is the subject of Personal Data.
              </span>
            </li>
          </ul>
          <br/>
          <br/>

          <h3><strong>Information Collection and Use</strong></h3>
          <p style={{textAlign:"justify"}} className="showContent">
          <span>We collect several different types of information for various purposes to provide and improve our Service to you.
          </span><br/>

          </p>
          <br/>

          <h3><strong>Types of Data Collected</strong></h3>

          <h4><strong>Personal Data</strong></h4>
          <p style={{textAlign:"justify"}} className="showContentChanged">
          <span>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
          </span><br/>
          </p>
          <ul className="role-ul-changed">
          <li className="role-li">

            <span>Email address
            </span>
          </li>
          <li className="role-li">

            <span>First name and last name
            </span>
          </li>
          <li className="role-li">

            <span>Address, State, Province, ZIP/Postal code, City
            </span>
          </li>
          <li className="role-li">

            <span>Cookies and Usage Data
            </span>
          </li>
        </ul>

        <p style={{textAlign:"justify"}} className="showContentChanged">
        <span>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or the instructions provided in any email we send.</span>

        </p>

          <br/>

          <h4><strong>Usage Data</strong></h4>
          <p style={{textAlign:"justify"}} className="showContentChanged">
          <span>We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </span>
          </p>
          <br/>

          <h4><strong>Tracking & Cookies Data</strong></h4>
          <p style={{textAlign:"justify"}} className="showContentChanged">
          <span>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</span><br/>
          <span>Cookies are files with a small amount of data which may include an anonymous unique identifier.</span>
          <span>Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.</span><br/>
          <span>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</span><br/>
          <span>Examples of Cookies we use:</span><br/>
          </p>

          <ul className="role-ul-changed">

          <li className="role-li">

            <span>Session Cookies. We use Session Cookies to operate our Service.
            </span>
          </li>
          <li className="role-li">

            <span>Preference Cookies. We use Preference Cookies to remember your preferences and various settings.
            </span>
          </li>
          <li className="role-li">

            <span>Security Cookies. We use Security Cookies for security purposes.
            </span>
          </li>
        </ul>

          <br/>
          <br/>

          <h3><strong>Use of Data</strong></h3>
          <p style={{textAlign:"justify"}} className="showContentChanged">

          <span>Melisxpress LLC uses the collected data for various purposes:</span><br/>
          </p>

          <ul className="role-ul-changed">

          <li className="role-li">
            <span>To provide and maintain our Service</span>
          </li>
          <li className="role-li">
            <span>To notify you about changes to our Service</span>
          </li>
          <li className="role-li">
            <span>To allow you to participate in interactive features of our Service when you choose to do so</span>
          </li>
          <li className="role-li">
            <span>To provide customer support</span>
          </li>
          <li className="role-li">
            <span>To gather analysis or valuable information so that we can improve our Service</span>
          </li>
          <li className="role-li">
            <span>To monitor the usage of our Service</span>
          </li>
          <li className="role-li">
            <span>To detect, prevent and address technical issues</span>
          </li>
          <li className="role-li">
            <span>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</span>
          </li>
        </ul>

          <br/>
          <br/>



          <h3><strong>Legal Basis for Processing Personal Data under the General Data Protection Regulation (GDPR)</strong></h3>
          <p style={{textAlign:"justify"}} className="showContentChanged">
          <span>If you are from the European Economic Area (EEA), Melisxpress LLC legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.</span><br/>
          <span>Melisxpress LLC may process your Personal Data because:</span><br/>
          </p>

          <ul className="role-ul-changed">

          <li className="role-li">
            <span>We need to perform a contract with you</span>
          </li>
          <li className="role-li">
            <span>You have given us permission to do so</span>
          </li>
          <li className="role-li">
            <span>The processing is in our legitimate interests and it is not overridden by your rights</span>
          </li>
          <li className="role-li">
            <span>For payment processing purposes</span>
          </li>
          <li className="role-li">
            <span>To comply with the law</span>
          </li>

        </ul>

          <br/>
          <br/>

          <h3><strong>Retention of Data</strong></h3>
          <p style={{textAlign:"justify"}} className="showContent">
          <span>Melisxpress LLC will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes and enforce our legal agreements and policies.</span><br/>
          <span>Melisxpress LLC will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.</span><br/>

          </p>
          <br/>

          <h3><strong>Transfer of Data</strong></h3>
          <p style={{textAlign:"justify"}} className="showContent">
          <span>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</span><br/>
          <span>If you are located outside the United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to the United States and process it there.</span><br/>
          <span>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</span><br/>
          <span>Melisxpress LLC will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</span><br/>

          </p>
          <br/>

          <h3><strong>Disclosure of Data</strong></h3>
          <h4><strong>Business Transaction</strong></h4>
          <p style={{textAlign:"justify"}} className="showContent">
          <span>If Melisxpress LLC is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.</span><br/>
          </p>


          <h4><strong>Disclosure for Law Enforcement</strong></h4>
          <p style={{textAlign:"justify"}} className="showContent">
          <span>Under certain circumstances, Melisxpress LLC. may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</span><br/>


          </p>


          <h4><strong>Legal Requirements</strong></h4>
          <p style={{textAlign:"justify"}} className="showContentChanged">
          <span>Melisxpress LLC. may disclose your Personal Data in the good faith belief that such action is necessary to:</span><br/>
          </p>
          <ul className="role-ul-changed">

          <li className="role-li">
            <span>To comply with a legal obligation</span>
          </li>
          <li className="role-li">
            <span>To protect and defend the rights or property of Melisxpress LLC.</span>
          </li>
          <li className="role-li">
            <span>To prevent or investigate possible wrongdoing in connection with the Service</span>
          </li>
          <li className="role-li">
            <span>To protect the personal safety of users of the Service or the public</span>
          </li>
          <li className="role-li">
            <span>To protect against legal liability</span>
          </li>

        </ul>
          <br/>
          <br/>


          <h3><strong>Security of Data</strong></h3>
          <p style={{textAlign:"justify"}} className="showContent">
          <span>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</span><br/>
          </p>
          <br/>

          <h3><strong>Your Data Protection Rights under the General Data Protection Regulation (GDPR)</strong></h3>
          <p style={{textAlign:"justify"}} className="showContent">
          <span>If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Melisxpress LLC aims to take reasonable steps to allow you to correct, amend, delete or limit the use of your Personal Data.</span><br/>
          <span>If you wish to be informed about what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.</span><br/>
          <span>In certain circumstances, you have the following data protection rights:</span><br/>
          </p>
          <ul className="role-ul-changed">

          <li className="role-li">
            <span>The right to access, update or delete the information we have on you. Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</span>
          </li>
          <li className="role-li">
            <span>The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.</span>
          </li>
          <li className="role-li">
            <span>The right to object. You have the right to object to our processing of your Personal Data.</span>
          </li>
          <li className="role-li">
            <span>The right of restriction. You have the right to request that we restrict the processing of your personal information.</span>
          </li>
          <li className="role-li">
            <span>The right to data portability. You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</span>
          </li>
          <li className="role-li">
            <span>The right to withdraw consent. You also have the right to withdraw your consent at any time where Melisxpress LLC relied on your consent to process your personal information.</span>
          </li>

        </ul>
        <p style={{textAlign:"justify"}} className="showContent">
          <span>Please note that we may ask you to verify your identity before responding to such requests.</span><br/>
          <span>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
</span><br/>
          </p>
          <br/>


          <h3><strong>Service Providers</strong></h3>
          <p style={{textAlign:"justify"}} className="showContent">
          <span>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</span><br/>
          <span>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</span><br/>
          </p>
          <br/>

          <h3><strong>Analytics</strong></h3>
          <p style={{textAlign:"justify"}} className="showContent">
          <span>We may use third-party Service Providers to monitor and analyse the use of our Service.</span><br/>
          </p>
          <ul className="role-ul-changed">

          <li className="role-li">
          <strong>Google Analytics</strong>
            <span>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.
You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity.
<br/>
For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="https://policies.google.com/privacy?hl=en" target="_blank">https://policies.google.com/privacy?hl=en</a></span>
          </li>
          </ul>
          <br/>

          <h3><strong>Behavioral Remarketing</strong></h3>
          <p style={{textAlign:"justify"}} className="showContent">
          <span>Melisxpress LLC uses remarketing services to advertise on third party websites to you after you visit our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.
</span><br/>
          </p>
          <ul className="role-ul-changed">

          <li className="role-li">
          <strong>Google Ads (AdWords)</strong>
            <span>Google Ads (AdWords) remarketing service is provided by Google Inc.
You can opt-out of Google Analytics for Display Advertising and customise the Google Display Network ads by visiting the Google Ads Settings page: <a href="http://www.google.com/settings/ads" target="_blank">http://www.google.com/settings/ads</a>
<br/>
Google also recommends installing the Google Analytics Opt-out Browser Add-on - <a href="https://tools.google.com/dlpage/gaoptout">https://tools.google.com/dlpage/gaoptout</a> - for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics.
<br/>
For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: <a href="https://policies.google.com/privacy?hl=en" target="_blank">https://policies.google.com/privacy?hl=en</a></span>
          </li>

          <li className="role-li">
          <strong>Facebook</strong>
            <span>Facebook remarketing service is provided by Facebook Inc.<br/>
            You can learn more about interest-based advertising from Facebook by visiting this page: <a href="https://www.facebook.com/help/164968693837950" target="_blank">https://www.facebook.com/help/164968693837950</a>
            <br/>
            To opt-out from Facebook's interest-based ads, follow these instructions from Facebook: <a href="https://www.facebook.com/help/568137493302217" target="_blank">https://www.facebook.com/help/568137493302217</a>
            <br/>
            Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA <a href="http://www.aboutads.info/choices/" target="_blank">http://www.aboutads.info/choices/</a>, the Digital Advertising Alliance of Canada in Canada <a href="http://youradchoices.ca/" target="_blank">http://youradchoices.ca/</a> or the European Interactive Digital Advertising Alliance in Europe <a href="http://www.youronlinechoices.eu/" target="_blank">http://www.youronlinechoices.eu/</a>, or opt-out using your mobile device settings.
            <br/>
            For more information on the privacy practices of Facebook, please visit Facebook's Data Policy: <a href="https://www.facebook.com/privacy/explanation" target="_blank">https://www.facebook.com/privacy/explanation</a></span>
          </li>


          </ul>
          <br/>



          <h3><strong>Payments</strong></h3>
          <p style={{textAlign:"justify"}} className="showContent">
          <span>We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).</span><br/>
          <span>We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, MasterCard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</span><br/>
          <span>The payment processors we work with are:</span><br/>
          </p>

          <ul className="role-ul-changed">

          <li className="role-li">
          <strong>PayPal</strong>
            <span>Their Privacy Policy can be viewed at <a href="https://www.paypal.com/webapps/mpp/ua/privacy-full" target="_blank">https://www.paypal.com/webapps/mpp/ua/privacy-full</a></span>
          </li>

          <li className="role-li">
          <strong>Stripe</strong>
            <span>Their Privacy Policy can be viewed at <a href="https://stripe.com/privacy" target="_blank">https://stripe.com/privacy</a></span>
          </li>
          </ul>
          <br/>

          <h3><strong>Links to Other Sites</strong></h3>
          <p style={{textAlign:"justify"}} className="showContent">
          <span>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</span><br/>
          <span>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</span><br/>
          </p>
          <br/>

          <h3><strong>Children's Privacy</strong></h3>
          <p style={{textAlign:"justify"}} className="showContent">
          <span>Our Service does not address anyone under the age of 18 ("Children").</span><br/>
          <span>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</span><br/>
          </p>
          <br/>


          <h3><strong>Changes to This Privacy Policy</strong></h3>
          <p style={{textAlign:"justify"}} className="showContent">
          <span>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</span><br/>
          <span>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</span><br/>
          <span>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</span><br/>
          <span></span><br/>
          </p>
          <br/>

          <h3><strong>Contact Us</strong></h3>
          <p style={{textAlign:"justify"}} className="showContent">
          <span>If you have any questions about this Privacy Policy, please contact us:</span><br/>
          </p>
          <ul className="role-ul-changed">

          <li className="role-li">

            <span>By email: <a href="mailto:support@melisxpress.com">support@melisxpress.com</a></span>
          </li>
          </ul>
          <br/>
          <br/>
          <br/>

        </div>
      </div>
    </div>
  );
};
export default PrivacyPolicy;
